Create application cluster module
solutionDrive/terraform-aws-application-cluster pull request #1
Opened 2018-03-06 15:04 UTC by solutionDrive-Alt

2018-03-06 15:15 UTC, sd-lueckel requested changes

2018-03-06 15:15 UTC, sd-lueckel commented on README.md
> +  domain   = "${var.oms_domain}"
suggest not to use 'oms' in variable name

2018-03-06 15:15 UTC, sd-lueckel commented on README.md
> +variable "application_cluster_elb_security_groups" {
suggest to use 'lb' instead of 'elb' because 'ApplicationLoadBalancer' != 'ElasticLoadBalancer'! Also used in other variables below

2018-03-06 15:52 UTC, sd-lueckel requested changes

2018-03-06 15:52 UTC, sd-lueckel commented on README.md
> +  default = "lbSecurityPolicy-TLS-1-2-2017-01"
I'm not sure if this change was intended

2018-03-06 15:52 UTC, sd-lueckel commented on variables.tf
> +  default = "lbSecurityPolicy-TLS-1-2-2017-01"
I'm not sure if this change was intended

2018-03-06 16:22 UTC, sd-lueckel approved these changes

2018-03-07 07:49 UTC, michz approved these changes

2018-03-07 08:03 UTC, merged